### ISSUE TITLE
Role fails to upgrade artifactory

### ISSUE THREAD

**Issue by jhulten** [bbaassssiiee/artifactory#1]
I updated the version variable and the role did not redownload or upgrade the application.

**Comment by bbaassssiiee** [comment]
TODO: needs a 'service artifactory stop' before to stop the old version, and cleanup after upgrade. Should be idempotent.

**Comment by jhulten** [comment]
I was thinking that you might want to move the data directory out of the versioned directory /opt/artifactory/artifactory-x.y.z

**Comment by ssbarnea** [comment]
ability to upgrade is quite an important part.

**Comment by bbaassssiiee** [comment]
data folder is moved, old version is deleted.
