### ISSUE TITLE
java check fails to detect java

### ISSUE THREAD

**Issue by ssbarnea** [bbaassssiiee/artifactory#2]
it seems that the logic for detecting if java is already installed failed as I had previously installed Oracle Java 8 on the target host and it seems that it decided to install openjdk7 instead, which was not quite desired.

**Comment by bbaassssiiee** [comment]
Installing openjdk7 supposedly an unwanted side effect. Presence of Java should be a test.

**Comment by bbaassssiiee** [comment]
Fixed with c8f9d54
