### ISSUE TITLE
Setting up without welcome screen

### ISSUE THREAD

**Issue by micabytes** [bbaassssiiee/artifactory#27]
Is there some way to configure this without having to deal with welcome screen - i.e., setting up repositories, etc., automatically?

Would prefer configuration as part of the code.

**Comment by bbaassssiiee** [comment]
If you know, then a pull-request is welcome. I don't use Artifactory anymore.

Sonatype Nexus is customizable with this role:

https://github.com/ansible-ThoTeam/nexus3-oss

**Comment by micabytes** [comment]
No worries. JFrog has their own ansible collections these days: https://github.com/jfrog/JFrog-Cloud-Installers
