### ISSUE TITLE
I was not even interested in using mysql for artifactory as postgresql seems like a much better pick

### ISSUE THREAD

**Issue by ssbarnea** [bbaassssiiee/artifactory#3]
It seems that it fails to install the mysql  jdbc drivers on Debian 8.1

```
TASK: [bbaassssiiee.artifactory | seboolean allow_user_mysql_connect] *********
failed: [repo.do.citrite.net] => {"failed": true}
msg: This module requires libselinux-python support

FATAL: all hosts have already failed -- aborting
```

In fact I was not even interested in using mysql for artifactory as postgresql seems like a much better pick, still the default settings failed to install.

**Comment by bbaassssiiee** [comment]
Debian is not supported. On RedHat like systems the bbaassssiiee.commoncentos role takes care of installing libselinux-python.

**Comment by bbaassssiiee** [comment]
The database can be toggled to PostgreSQL using this in your group_vars:

  features:
    mysql: False 
    postgresql: True

**Comment by bbaassssiiee** [comment]
Changed title of issue
