### ISSUE TITLE
Centos 6 - tomcat fails to start using 'service artifactory start'

### ISSUE THREAD

**Issue by RobertLos** [bbaassssiiee/artifactory#6]
In the file ~/tasks/install.yml the 'create user to run artifactory' (line 17) role is defined by:
user: name={{artifactory_username}} home=/opt/artifactory/ shell=/bin/false system=true

This creates a problem in starting via service or /etc/init.d/artifactory.

A solution was changing this line to:
user: name={{artifactory_username}} home=/opt/artifactory/ shell=/bin/bash system=true

hope this helps

**Comment by bbaassssiiee** [comment]
pushed
